(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],safe=v=>typeof v==='string'?v:'';
async function json(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(path);return r.json()}
function makeWave(){const w=$('#wave');if(!w)return;for(let i=0;i<54;i++){const b=document.createElement('i');b.style.height=(7+Math.abs(Math.sin(i*.71))*29)+'px';b.style.animationDelay=(-i*.035)+'s';w.appendChild(b)}}
function makeScratches(){const root=$('#scratches');if(!root)return;for(let i=0;i<17;i++){const s=document.createElement('i'),diag=i%3===0;s.className='scratch'+(diag?' diag':'')+(i%8===0?' red':'');s.style.left=(3+Math.random()*94)+'vw';s.style.top=(-20+Math.random()*80)+'vh';s.style.setProperty('--dur',(4.8+Math.random()*10)+'s');s.style.setProperty('--delay',(-Math.random()*14)+'s');s.style.setProperty('--rot',(diag?(-18+Math.random()*32):(-4+Math.random()*8))+'deg');root.appendChild(s)}}
function text(tag,value){const n=document.createElement(tag);n.textContent=value;return n}
async function hydrate(){const phase=$('#phase'),field=$('#fieldData'),canon=$('#canon');try{const [ledger,experiment,logbook]=await Promise.all([json('/grimoire/ledger.json'),json('/grimoire/experiment.json'),json('/grimoire/logbook.json')]);const p=safe(ledger.phase||experiment.phase||ledger.current_phase).toUpperCase();if(p)phase.textContent=p;const entries=Array.isArray(logbook)?logbook:(logbook.entries||logbook.logbook||[]);field.replaceChildren();if(entries.length)entries.slice(-6).reverse().forEach(e=>{const a=document.createElement('article');a.append(text('b',safe(e.title||e.event||e.type||e.id||'RETURN')),text('p',safe(e.date||e.timestamp||e.at||'')));field.append(a)});else field.append(text('p','NO PUBLIC RETURN PROMOTED WITHOUT CANONICAL DATA.'));canon.textContent='CANON / PERSISTENT / GIT-BACKED'}catch(e){field.replaceChildren(text('p','SOURCE UNAVAILABLE · NOTHING SYNTHETIC INSERTED.'));canon.textContent='CANON / SOURCE UNAVAILABLE'}}
const audio=$('#audio'),play=$('#play'),title=$('#nowTitle'),state=$('#nowState');
function sync(){if(!audio||!play)return;const on=!audio.paused&&!audio.ended;play.querySelector('span').textContent=on?'Ⅱ':'▶';$('#wave').style.opacity=on?'1':'.45';if(state)state.textContent=on?'REPRODUCIENDO':'MASTER EN REPOSITORIO'}
async function toggle(){if(audio.paused){try{await audio.play()}catch(e){if(state)state.textContent='PLAYBACK BLOQUEADO POR EL NAVEGADOR'}}else audio.pause();sync()}
if(play&&audio){play.addEventListener('click',toggle);audio.addEventListener('play',sync);audio.addEventListener('pause',sync);audio.addEventListener('ended',sync)}
$$('.track-play').forEach(b=>b.addEventListener('click',async()=>{const card=b.closest('.track'),src=card?.dataset.src;if(!src||!audio)return;if(audio.getAttribute('src')!==src){audio.src=src;title.textContent=card.dataset.title||'KXTXR'}await toggle()}));
const nav=$$('.nav nav a');const io=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return;const key=e.target.dataset.nav;nav.forEach(a=>a.classList.toggle('active',a.textContent.trim()===key));document.body.dataset.scene=key}),{threshold:.48});$$('.scene').forEach(s=>io.observe(s));
let tx=0,ty=0,cx=0,cy=0;addEventListener('pointermove',e=>{tx=(e.clientX/innerWidth-.5)*8;ty=(e.clientY/innerHeight-.5)*5},{passive:true});function drift(){cx+=(tx-cx)*.035;cy+=(ty-cy)*.035;document.documentElement.style.setProperty('--mx',cx+'px');document.documentElement.style.setProperty('--my',cy+'px');requestAnimationFrame(drift)}
makeWave();makeScratches();hydrate();sync();if(!matchMedia('(prefers-reduced-motion: reduce)').matches)drift();
})();