/* KXTXR — layers.js
   Fallback model + canonical JSON loader.
   Canon source: ./grimoire/kxtxr-grimoire-longitudinal-canon-v3.json */

const KXTXR_IDENTITY={canonTitle:"THE WOUND THAT LEARNED TO RETURN",coreSentence:"A signal persists long enough to remember what it was, transform without disappearing, and return carrying evidence of its own passage.",axiom:"NO OPTIMICES. REGISTRA."};
const LAYER_ORDER=["creation","field","frecuency","lab","notes","objects","reconstructions","tminus"];
const FALLBACK_LAYERS={
creation:{title:"Creation",subtitle:"Origin Codex",status:"GENESIS ACTIVE",visualType:"origin-codex",origin:KXTXR_IDENTITY.coreSentence,fragments:["1347 — THE FIRST WOUND","THE WOUND LEARNS INSCRIPTION","THE MARK LEARNS RHYTHM"],timeline:[{when:"1347",label:"THE FIRST WOUND"},{when:"MANUSCRIPT",label:"INSCRIPTION"},{when:"RITUAL",label:"RHYTHM"},{when:"NETWORK",label:"MEMORY"}],meta:{source:"Lore Archive",integrity:"canon",mode:"Foundational"}},
field:{title:"Field",subtitle:"Signal Observatory",status:"REM618 TRACE ACTIVE",visualType:"timeline-signal",fragments:["REM618 — THE WOUND ENTERS THE FIELD","OPENING / DETECTION / PRIMA MATERIA","INTERVAL — SILENCE AS MATERIAL"],events:[{when:"2026.06.11",label:"REM618"},{when:"INTERVAL",label:"SILENCE"},{when:"2026.08",label:"111"}],meta:{source:"REM618",integrity:"preserved",mode:"Observed"}},
frecuency:{title:"Frecuency",subtitle:"Signal Grammar",status:"CHAIN ONLINE",visualType:"sequence-map",sequence:["REM618","111","RETURN"],formula:"SIGNAL -> SILENCE -> TRACE -> MEMORY -> RETURN -> NEW SIGNAL",fragments:["111 DOES NOT REPLACE REM618","NEXT FORM REMAINS UNWRITTEN"],meta:{source:"Sequence Core",integrity:"linked",mode:"Longitudinal"}},
lab:{title:"Alchemical Lab",subtitle:"Reaction Matrix",status:"REACTION OPEN",visualType:"network-matrix",nodes:["REM618","111","RETURN","NOTES","OBJECTS","SFI"],links:[[0,1],[1,2],[2,3],[2,4],[2,5]],fragments:["RETURN IS THE TRANSMUTATION CHAMBER","CONNECT ARTIFACT / NOTE / SIGNAL / RESIDUE"],meta:{source:"Lab Core",integrity:"active",mode:"Reactive"}},
notes:{title:"Notes",subtitle:"Memory Ledger",status:"THE BOOK REMEMBERS",visualType:"ledger-stack",noteTypes:["ORIGIN","OBSESSION","DECISION","CHANGE","PERSISTENCE","DISCARDED_PATH","FIELD_ECHO","RETURN","FUTURE_FRAGMENT"],fragments:["A NOTE SHOWS HOW ONE STATE PRODUCED ANOTHER","WHAT CHANGED / WHAT PERSISTED / WHAT REMAINS"],meta:{source:"Persistent Notes",integrity:"longitudinal",mode:"Memory"}},
objects:{title:"Objects",subtitle:"Artifact Vault",status:"VAULT READY",visualType:"artifact-grid",catalogue:{REM618:"opening / detection","111":"visual archive / genealogy","easter_egg":"hidden connector","LUGAR LUNAR":"nocturnal permanence",KYRIE:"emotional center",ESPINAS:"friction / tension",BLVCK:"rupture","E.D.":"threshold / closure"},meta:{source:"Object Registry",integrity:"material",mode:"Artifact"}},
reconstructions:{title:"Reconstructions",subtitle:"Future Branches",status:"EMERGENCE PENDING",visualType:"branch-tree",branches:[{label:"easter_egg",state:"pending"},{label:"LUGAR LUNAR",state:"pending"},{label:"KYRIE",state:"emerging"},{label:"ESPINAS",state:"unstable"},{label:"BLVCK",state:"unstable"}],rule:"The next node inherits the strongest surviving signal from RETURN, not a release calendar.",meta:{source:"Projection Engine",integrity:"unresolved",mode:"Prospective"}},
tminus:{title:"T-0.00001",subtitle:"Precursor Archive",status:"PRECURSOR ACCESS",visualType:"deep-archive",dossier:[{k:"Role",v:"Trusted external observer / optional analytical instrument"},{k:"Relationship",v:"KXTXR may lend objects to SFI for observation, MIHM or longitudinal study"},{k:"Boundary",v:"SFI does not author KXTXR canon"}],fragments:["BEFORE VISIBLE KXTXR: MOTIVE / BIO / ATTRACTOR / PRECURSOR"],meta:{source:"Precursor Archive",integrity:"bounded",mode:"Archaeological"}}};
let layers=structuredClone(FALLBACK_LAYERS);
async function loadKxtxrLayers(){try{const r=await fetch('./grimoire/kxtxr-grimoire-longitudinal-canon-v3.json',{cache:'no-store'});if(!r.ok)throw new Error(r.status);const c=await r.json();const spine=c.lore_spine||[];const role=c.catalogue_roles||{};const ret=c.return_design||{};const notes=c.notes_architecture||{};const ext=(c.external_relationships||{}).SFI||{};layers.creation.origin=c.identity?.core_sentence||layers.creation.origin;layers.creation.fragments=spine.slice(0,3).map(x=>`${x.node} — ${x.title}`);layers.creation.timeline=spine.slice(0,5).map(x=>({when:x.node,label:x.state}));layers.field.fragments=spine.filter(x=>['EMISSION','SILENCE','EMERGENCE','RETURN'].includes(x.state)).slice(0,4).map(x=>`${x.node} — ${x.title}`);layers.frecuency.formula=c.signal_grammar?.canonical_formula||layers.frecuency.formula;layers.frecuency.sequence=['REM618','111','RETURN'];layers.frecuency.fragments=[c.signal_grammar?.meaning||'',spine.find(x=>x.state==='UNWRITTEN')?.selection_rule||''].filter(Boolean);layers.lab.fragments=[ret.rule||'',`RETURN LAYERS: ${(ret.return_layers||[]).map(x=>x.id).join(' / ')}`];layers.notes.noteTypes=notes.note_types||layers.notes.noteTypes;layers.notes.fragments=[notes.principle||'',notes.continuity_rule||''].filter(Boolean);layers.objects.catalogue=role;const next=spine.find(x=>x.state==='UNWRITTEN');layers.reconstructions.branches=(next?.candidate_lineage||[]).slice(0,7).map((x,i)=>({label:x.split(' / ')[0],state:i<2?'pending':i<4?'emerging':'unstable'}));layers.reconstructions.rule=next?.selection_rule||layers.reconstructions.rule;layers.tminus.dossier=[{k:'Role',v:ext.role||''},{k:'Relationship',v:ext.relationship||''},{k:'Boundary',v:ext.boundary||''}];return c}catch(e){console.warn('KXTXR canon fallback active',e);return null}}
