(function(){
'use strict';
const q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)];
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const lerp=(a,b,t)=>a+(b-a)*t;
const ease=t=>t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2;
const field=q('#kxLayerfield'), fxfield=q('#kxFxfield'), progressBar=q('#kxProgress i');
const sections=qa('#kxTrack section');
const network=q('#kxNetwork'), sound=q('#kxSound'), audio=q('#kx111');
const AS='/artist/assets/';
const MOTIONS={top:{x:0,y:-58,s:.86,r:-5},bottom:{x:0,y:65,s:.88,r:4},left:{x:-72,y:0,s:.92,r:-8},right:{x:72,y:0,s:.92,r:8},depth:{x:0,y:0,s:.22,r:13},cornerTL:{x:-62,y:-46,s:.65,r:-16},cornerTR:{x:64,y:-44,s:.62,r:15},cornerBL:{x:-67,y:50,s:.7,r:12},cornerBR:{x:68,y:52,s:.7,r:-14},spin:{x:42,y:-18,s:.35,r:160},snap:{x:-18,y:28,s:1.7,r:-18},float:{x:28,y:-38,s:.76,r:8},rise:{x:-20,y:68,s:.82,r:-6}};
function elImg(id,src,klass=''){const e=document.createElement('img');e.id=id;e.className='kx-layer '+klass;e.src=AS+src;e.alt='';e.draggable=false;field.appendChild(e);return e}
function fx(id,klass,html=''){const e=document.createElement('div');e.id=id;e.className='kx-fx '+klass;e.innerHTML=html;fxfield.appendChild(e);return e}
function ui(id){return fx(id,'kx-ui','<div class="wave"></div><div class="bar"></div><div class="grid"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><div class="knobs"><i></i><i></i><i></i></div>')}
const E={tired:elImg('edwingTired','edwing-tired.png'),reach:elImg('edwingReach','edwing-reach.png'),energy:elImg('edwing111','edwing-111.png'),guitarMan:elImg('edwingGuitar','edwing-guitar.png'),guitar:elImg('propGuitar','guitar.png','prop'),mic:elImg('propMic','mic.png','prop'),headphones:elImg('propHeadphones','headphones.png','prop micro'),laptop:elImg('propLaptop','laptop.png','prop'),keyboard:elImg('propKeyboard','keyboard.png','prop'),drumpad:elImg('propDrumpad','drumpad.png','prop'),speaker:elImg('propSpeaker','speaker.png','prop'),interface:elImg('propInterface','interface.png','prop micro'),cassette:elImg('propCassette','cassette.png','prop micro'),coffee:elImg('propCoffee','coffee.png','prop micro'),phone:elImg('propPhone','phone.png','prop micro'),light:elImg('propLight','light.png','prop micro'),crowd:elImg('crowd','crowd.png','crowd'),beep:fx('fxBeep','kx-onoma','BEEP!'),vrrrm:fx('fxVrrrm','kx-onoma','VRRRM'),dum:fx('fxDum','kx-onoma','DUM!'),mark111:fx('fx111','kx-111','111'),boom:fx('fxBoom','kx-onoma','BOOM!'),ring:fx('fxRing','kx-energy-ring'),upload:ui('uiUpload'),route:ui('uiRoute')};
const bg={room:q('[data-bg="room"]'),studio:q('[data-bg="studio"]'),stage:q('[data-bg="stage"]'),kaiju:q('[data-bg="kaiju"]')};
const all=[...Object.values(E)];
function state(el,o={}){el.dataset.x=o.x??0;el.dataset.y=o.y??0;el.dataset.s=o.s??1;el.dataset.r=o.r??0;el.dataset.o=o.o??0;el.dataset.z=o.z??10}
function hideAll(){all.forEach(e=>state(e,{o:0,s:.88}));Object.values(bg).forEach(b=>b.style.opacity=0);network.style.opacity=0;network.classList.remove('is-active')}
function place(el,opt){const {x=0,y=0,s=1,r=0,o=1,z=12}=opt;state(el,{x,y,s,r,o,z})}
function renderEl(el){const x=+el.dataset.x||0,y=+el.dataset.y||0,s=+el.dataset.s||1,r=+el.dataset.r||0,o=+el.dataset.o||0,z=+el.dataset.z||10;el.style.zIndex=z;el.style.opacity=o;el.style.transform=`translate(calc(-50% + ${x}vw),calc(-50% + ${y}vh)) scale(${s}) rotate(${r}deg)`}
function reveal(el,motion,to,p){const m=MOTIONS[motion]||MOTIONS.depth,t=ease(clamp(p));place(el,{x:lerp(m.x,to.x??0,t),y:lerp(m.y,to.y??0,t),s:lerp(m.s,to.s??1,t),r:lerp(m.r,to.r??0,t),o:lerp(0,to.o??1,t),z:to.z??12})}
function setBg(which,push=1){Object.entries(bg).forEach(([k,b])=>{b.style.opacity=k===which?1:0;b.style.transform=`scale(${1.06+push*.018}) translate3d(${push*.15}%,${-push*.08}%,0)`})}
function sceneWake(p){setBg('room',p);reveal(E.tired,'cornerBL',{x:-14,y:5,s:.94,r:-2,z:22},clamp(p/.42));reveal(E.phone,'bottom',{x:27,y:21,s:.9,r:9,z:28},clamp((p-.12)/.3));reveal(E.coffee,'cornerTR',{x:-31,y:24,s:.88,r:-8,z:29},clamp((p-.24)/.28));reveal(E.beep,'right',{x:20,y:-20,s:.72,r:8,z:40},clamp((p-.36)/.24))}
function sceneSignal(p){setBg('room',.6+p);reveal(E.reach,'left',{x:-10,y:4,s:.9,r:0,z:23},clamp(p/.34));reveal(E.laptop,'cornerTR',{x:23,y:-7,s:.88,r:-5,z:26},clamp((p-.06)/.3));reveal(E.headphones,'top',{x:30,y:18,s:.78,r:8,z:30},clamp((p-.2)/.25));reveal(E.speaker,'right',{x:34,y:4,s:.78,r:-4,z:21},clamp((p-.34)/.26));reveal(E.cassette,'spin',{x:6,y:26,s:.95,r:8,z:36},clamp((p-.48)/.24))}
function sceneGuitar(p){setBg('studio',p);reveal(E.guitar,'bottom',{x:-30,y:2,s:.9,r:-9,z:18},clamp(p/.28));reveal(E.guitarMan,'depth',{x:1,y:3,s:.94,r:0,z:25},clamp((p-.1)/.42));reveal(E.vrrrm,'cornerTR',{x:28,y:-23,s:.65,r:9,z:45},clamp((p-.38)/.25));reveal(E.interface,'left',{x:-31,y:24,s:.82,r:6,z:30},clamp((p-.48)/.24))}
function sceneProducer(p){setBg('studio',.4+p);reveal(E.reach,'cornerBL',{x:-8,y:8,s:.88,r:-2,z:24},clamp(p/.3));reveal(E.keyboard,'bottom',{x:8,y:28,s:.92,r:-4,z:26},clamp((p-.08)/.3));reveal(E.drumpad,'right',{x:30,y:19,s:.72,r:7,z:32},clamp((p-.2)/.28));reveal(E.mic,'top',{x:-27,y:-7,s:.7,r:-6,z:34},clamp((p-.32)/.23));reveal(E.dum,'left',{x:-27,y:-25,s:.62,r:-9,z:44},clamp((p-.48)/.2));reveal(E.speaker,'cornerTR',{x:34,y:-12,s:.72,r:3,z:18},clamp((p-.57)/.2))}
function sceneEnergy(p){setBg('studio',1+p);reveal(E.energy,'rise',{x:0,y:3,s:.96,r:0,z:28},clamp(p/.4));reveal(E.ring,'depth',{x:0,y:0,s:1,r:lerp(-60,10,p),z:19},clamp((p-.08)/.36));reveal(E.mark111,'right',{x:24,y:-14,s:1,r:-7,z:38},clamp((p-.34)/.25));q('#kxSpeedlines').style.opacity=clamp((p-.18)/.45)*.76;q('#kxSpeedlines').style.transform=`scale(${1+p*.35}) rotate(${p*8}deg)`}
function sceneRelease(p){setBg('studio',1.2+p);reveal(E.upload,'left',{x:-19,y:3,s:.9,r:-3,z:30},clamp(p/.35));reveal(E.route,'right',{x:18,y:10,s:.82,r:4,z:31},clamp((p-.16)/.34));reveal(E.cassette,'top',{x:0,y:-27,s:1.05,r:12,z:35},clamp((p-.35)/.25));reveal(E.phone,'bottom',{x:31,y:24,s:.82,r:-10,z:35},clamp((p-.52)/.2))}
function sceneLive(p){setBg('stage',p);reveal(E.crowd,'bottom',{x:0,y:0,s:1.05,r:0,z:14},clamp(p/.34));reveal(E.guitarMan,'bottom',{x:0,y:8,s:.9,r:-2,z:28},clamp((p-.08)/.34));reveal(E.mic,'top',{x:-4,y:-9,s:.74,r:4,z:34},clamp((p-.24)/.26));reveal(E.light,'cornerTR',{x:34,y:-24,s:.82,r:14,z:40},clamp((p-.4)/.2));reveal(E.dum,'left',{x:-31,y:-19,s:.58,r:-10,z:46},clamp((p-.54)/.18))}
function sceneKaiju(p){setBg('kaiju',p);reveal(E.reach,'left',{x:-28,y:12,s:.72,r:1,z:33},clamp(p/.35));reveal(E.crowd,'bottom',{x:0,y:0,s:1.08,r:0,z:16},clamp(p/.2));if(p>.48)reveal(E.boom,'depth',{x:15,y:19,s:1.1,r:-8,z:49},clamp((p-.48)/.28));q('#kxSpeedlines').style.opacity=clamp((p-.32)/.4)*.9;q('#kxSpeedlines').style.transform=`scale(${1.2+p*.6}) rotate(${-8+p*18}deg)`}
function sceneNetwork(p){setBg('kaiju',1.4);const t=ease(clamp((p-.05)/.55));network.style.opacity=t;network.classList.toggle('is-active',t>.92);q('#kxSpeedlines').style.opacity=(1-t)*.55}
const SCENES=[sceneWake,sceneSignal,sceneGuitar,sceneProducer,sceneEnergy,sceneRelease,sceneLive,sceneKaiju,sceneNetwork];
function update(){const y=scrollY,vh=innerHeight;let idx=0,local=0;for(let i=0;i<sections.length;i++){const r=sections[i].getBoundingClientRect();if(r.top<=vh*.5)idx=i;if(r.top<=0&&r.bottom>=vh){local=clamp((-r.top)/(r.height-vh||1));idx=i;break}else if(r.top>0&&i===0){idx=0;local=0}}const total=Math.max(1,document.documentElement.scrollHeight-vh);progressBar.style.height=(clamp(y/total)*100)+'%';hideAll();q('#kxSpeedlines').style.opacity=0;SCENES[idx]?.(local);all.forEach(renderEl)}
let raf=0;function tick(){raf=0;update()}function onScroll(){if(!raf)raf=requestAnimationFrame(tick)}
addEventListener('scroll',onScroll,{passive:true});addEventListener('resize',onScroll,{passive:true});
async function hydrateNetwork(){try{const r=await fetch('/grimoire/artist-presence.json',{cache:'no-store'});if(!r.ok)return;const d=await r.json(),gateways=d.network_gateways||[];qa('#kxNetwork a').forEach(a=>{const key=a.dataset.network,hit=gateways.find(g=>String(g.label||'').toUpperCase().includes(key));if(hit?.url)a.href=hit.url;else if(!a.getAttribute('href')){a.removeAttribute('href');a.setAttribute('aria-disabled','true')}})}catch(_e){}}
async function load111(){const candidates=['/assets/111.wav','/assets/111.mp3','/assets/KXTXR - 111 master final.wav','/assets/KXTXR-111-master.wav'];for(const src of candidates){try{const r=await fetch(src,{method:'HEAD',cache:'no-store'});if(r.ok){audio.src=src;return true}}catch(_e){}}sound.classList.add('is-muted');sound.setAttribute('aria-label','111 soundtrack file is not present');return false}
sound.addEventListener('click',async()=>{if(!audio.src){const ok=await load111();if(!ok)return}if(audio.paused){try{await audio.play();sound.classList.remove('is-muted')}catch(_e){sound.classList.add('is-muted')}}else{audio.pause();sound.classList.add('is-muted')}});
async function init(){hydrateNetwork();const has=await load111();if(has){try{await audio.play();sound.classList.remove('is-muted')}catch(_e){sound.classList.add('is-muted')}}update()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
