const SCENES=[
 {state:'OBJECT',k:'01 · THE OBJECT',t:'The signal has a body.',c:'Before it becomes interface, it exists as an object: sealed, indexed, persistent.',signal:18},
 {state:'ACTIVATION',k:'02 · FIRST CONTACT',t:'The cover begins to answer.',c:'A minimal disturbance is enough. The mark brightens; telemetry becomes visible around the object.',signal:31},
 {state:'TRANSITION',k:'03 · THE TRANSITION',t:'The object loses its fixed state.',c:'Runes separate from the surface. The laboratory stops behaving as background and becomes an instrument.',signal:48},
 {state:'OPENING',k:'04 · THE OPENING',t:'The spine becomes an axis.',c:'The book opens. Its pages do not explain the signal; they expose a field in which it can be inspected.',signal:67},
 {state:'DASHBOARD',k:'05 · SIGNAL DASHBOARD',t:'The archive becomes operational.',c:'REM618, 111, memory residue, origin trace and node relations enter the same observable surface.',signal:86},
 {state:'LIVE',k:'06 · LIVE FIELD',t:'Nothing here is static.',c:'Graphs advance, nodes pulse and runes change luminance. The image is a carrier; the browser supplies time.',signal:99},
 {state:'RESIDUE',k:'07 · RETURN',t:'Brightness falls. Persistence remains.',c:'The system keeps enough energy to remain legible. What changed is recorded as viewer memory.',signal:41}
];
const FILES={archive:'/grimoire/ledger.json',signals:'/grimoire/experiment.json',memory:'/grimoire/snapshots.json',lab:'/grimoire/retrolongitudinal.json',about:'/grimoire/story.json'};
const KEY='kxtxr.viewer-memory.v2',VIEWER_KEY='kxtxr.viewer-id.v1';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function viewerId(){let id=localStorage.getItem(VIEWER_KEY);if(!id){id=(crypto.randomUUID?.()||('kx-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2)));localStorage.setItem(VIEWER_KEY,id)}return id}
const VIEWER_ID=viewerId();
function blankMemory(){return{visits:0,scenes:{},panels:{},firstSeen:new Date().toISOString()}}
function loadMemory(){try{return JSON.parse(localStorage.getItem(KEY))||blankMemory()}catch{return blankMemory()}}
const app={scene:0,last:Date.now(),audio:false,ctx:null,memory:loadMemory(),panel:null};let remoteTimer;
function saveMemory(sync=true){app.memory.lastSeen=new Date().toISOString();app.memory.lastScene=app.scene;localStorage.setItem(KEY,JSON.stringify(app.memory));$('#memoryState').textContent=`MEMORY · ${Object.keys(app.memory.scenes||{}).length}/7`;if(sync){clearTimeout(remoteTimer);remoteTimer=setTimeout(pushRemoteMemory,850)}}
async function pushRemoteMemory(){try{await fetch(`/api/ai-memory?id=${encodeURIComponent(VIEWER_ID)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(app.memory),keepalive:true})}catch{}}
async function pullRemoteMemory(){try{const r=await fetch(`/api/ai-memory?id=${encodeURIComponent(VIEWER_ID)}`,{cache:'no-store'});if(!r.ok)return;const x=await r.json();if(x.memory&&Date.parse(x.memory.lastSeen||0)>Date.parse(app.memory.lastSeen||0)){app.memory=x.memory;saveMemory(false)}}catch{}}
function touchScene(i){const s=app.memory.scenes[i]||(app.memory.scenes[i]={enters:0,ms:0});s.enters++;saveMemory()}
function toast(s){const e=$('#memoryToast');e.textContent=s;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),1800)}
function initRunes(){const chars=['ᚱ','ᛟ','ᛗ','ᛉ','ᚷ','ᛇ','ᛞ','ᚾ','ᛜ','⌬','⌁','⟡','⧖','⋈','◈'],root=$('#runeField');for(let i=0;i<48;i++){const e=document.createElement('span');e.className='rune';e.textContent=chars[Math.floor(Math.random()*chars.length)];e.style.left=`${3+Math.random()*94}%`;e.style.top=`${8+Math.random()*84}%`;e.style.setProperty('--d',`${2.5+Math.random()*5}s`);e.style.setProperty('--delay',`${-Math.random()*6}s`);root.appendChild(e)}}
function progress(){const e=$('#experience'),r=e.getBoundingClientRect(),t=e.offsetHeight-innerHeight;return Math.max(0,Math.min(1,-r.top/t))}
function setScene(i,force=false){i=Math.max(0,Math.min(6,i));if(i===app.scene&&!force)return;const now=Date.now(),old=app.memory.scenes[app.scene];if(old)old.ms=(old.ms||0)+(now-app.last);app.last=now;app.scene=i;$$('.scene').forEach((e,n)=>e.classList.toggle('active',n===i));$$('.scene-rail button').forEach((e,n)=>e.classList.toggle('active',n===i));const s=SCENES[i],card=$('#narrativeCard');card.classList.add('change');setTimeout(()=>{$('#sceneIndex').textContent=`0${i+1} / 07`;$('#sceneState').textContent=s.state;$('#sceneTelemetry').textContent=`SIGNAL ${s.signal}%`;$('#narrativeKicker').textContent=s.k;$('#narrativeTitle').textContent=s.t;$('#narrativeCopy').textContent=s.c;card.classList.remove('change')},230);$('#dashboardLayer').classList.toggle('live',i>=4&&i<=5);touchScene(i);if(app.audio)ping(120+40*i,.025)}
function onScroll(){const p=progress();setScene(Math.min(6,Math.floor(p*7)));drawSignal(p)}
function jump(i){const e=$('#experience'),y=e.offsetTop+(i/7)*(e.offsetHeight-innerHeight)+2;scrollTo({top:y,behavior:'smooth'});closeDrawer()}
function prepCanvas(c){const d=Math.min(2,devicePixelRatio||1),w=c.clientWidth,h=c.clientHeight;if(c.width!==w*d||c.height!==h*d){c.width=w*d;c.height=h*d}const x=c.getContext('2d');x.setTransform(d,0,0,d,0,0);x.clearRect(0,0,w,h);return{x,w,h}}
function drawSignal(p=0){const{x,w,h}=prepCanvas($('#signalCanvas'));if(app.scene<4)return;x.strokeStyle=`rgba(235,164,54,${app.scene===5?.38:.18})`;x.lineWidth=.8;x.beginPath();for(let i=0;i<w;i+=5){const y=h*.78+Math.sin(i*.045+p*40)*7+Math.sin(i*.013+p*11)*12+(Math.random()-.5)*3;i?x.lineTo(i,y):x.moveTo(i,y)}x.stroke()}
function animateNodes(t){const{x,w,h}=prepCanvas($('#nodeCanvas'));if(app.scene>=4){const pts=[];for(let i=0;i<18;i++){const a=i/18*Math.PI*2+t*.00003*(i%3-1),r=90+(i%5)*18;pts.push([w*.5+Math.cos(a)*r,h*.4+Math.sin(a)*r*.62])}x.strokeStyle='rgba(208,142,39,.11)';for(let i=0;i<pts.length;i++)for(let j=i+1;j<pts.length;j++)if((i*j)%7===0){x.beginPath();x.moveTo(...pts[i]);x.lineTo(...pts[j]);x.stroke()}pts.forEach((p,i)=>{const q=.4+.6*Math.sin(t*.003+i);x.fillStyle=`rgba(255,177,58,${.2+.45*Math.max(0,q)})`;x.beginPath();x.arc(p[0],p[1],1.2+1.8*Math.max(0,q),0,Math.PI*2);x.fill()})}requestAnimationFrame(animateNodes)}
function initAudio(){if(app.ctx)return;app.ctx=new(window.AudioContext||window.webkitAudioContext)();const g=app.ctx.createGain(),o=app.ctx.createOscillator(),l=app.ctx.createOscillator(),lg=app.ctx.createGain();g.gain.value=.015;o.frequency.value=55;l.frequency.value=.08;lg.gain.value=4;l.connect(lg);lg.connect(o.frequency);o.connect(g);g.connect(app.ctx.destination);o.start();l.start()}
function ping(f=220,v=.03){if(!app.ctx)return;const o=app.ctx.createOscillator(),g=app.ctx.createGain();o.frequency.value=f;g.gain.setValueAtTime(v,app.ctx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,app.ctx.currentTime+.3);o.connect(g);g.connect(app.ctx.destination);o.start();o.stop(app.ctx.currentTime+.31)}
function toggleSound(){app.audio=!app.audio;if(app.audio){initAudio();app.ctx.resume();ping(330,.04)}$('#soundToggle').textContent=app.audio?'●':'◉';toast(app.audio?'AMBIENT SIGNAL ON':'AMBIENT SIGNAL OFF')}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function memoryMarkup(){const m=app.memory;return `<div class="memory-box"><small>VIEWER PERSISTENCE / LOCAL-FIRST + OPTIONAL CLOUD DURABILITY</small><div class="metrics"><div class="metric"><small>VISITS</small><b>${m.visits||0}</b></div><div class="metric"><small>SCENES TOUCHED</small><b>${Object.keys(m.scenes||{}).length}/7</b></div></div><button id="exportMemory">EXPORT MEMORY</button><button id="clearMemory">CLEAR LOCAL MEMORY</button></div>`}
function renderPanel(k,d){if(k==='archive')return `<div class="metrics"><div class="metric"><small>STATE</small><b>${esc(d.current_state||'OPEN')}</b></div><div class="metric"><small>AXIOM</small><b>${esc(d.axiom||'OBSERVE')}</b></div></div>${(d.lineage||[]).map(a=>`<article class="record"><small>${esc(a.id)} · ${esc(a.epistemic_class)}</small><h3>${esc(a.label)} / ${esc(a.state)}</h3><p>${esc(a.function)}</p></article>`).join('')}`;if(k==='signals')return `<article class="record"><small>PRIMARY QUESTION</small><h3>${esc(d.primary_question||d.state)}</h3><p>Visual motion is presentation. Canonical measurements remain in the Git-backed ledger.</p></article>`;if(k==='memory')return memoryMarkup()+(d.snapshots||[]).map(s=>`<article class="record"><small>${esc(s.id)} · ${esc(s.captured_at)}</small><h3>${esc(s.state)}</h3><p>${esc(s.summary)}</p></article>`).join('');if(k==='lab')return `<article class="record"><small>RETROLONGITUDINAL READING</small><h3>${esc(d.question)}</h3><p>Observed, inferred and missing states remain separated.</p></article>`+(d.periods||[]).map(p=>`<article class="record"><small>${esc(p.id)} · ${esc(p.label)}</small><h3>${(p.observed||[]).length} observed / ${(p.inferred||[]).length} inferred</h3><p>${esc((p.observed||[])[0]||'No observed statement')}</p></article>`).join('');return `<article class="record"><small>NARRATIVE SPINE</small><h3>${esc(d.title||'KXTXR')}</h3><p>The interface is a visual narrative layer over canonical state.</p></article>`+(d.chapters||[]).map(c=>`<article class="record"><small>${esc(c.id)} · ${esc(c.label)}</small><h3>${esc(c.title)}</h3><p>${esc(c.text)}</p></article>`).join('')}
async function openPanel(k){app.panel=k;const titles={archive:'ARCHIVE',signals:'SIGNALS',memory:'MEMORY',lab:'LAB',about:'ABOUT / STORY'};$('#drawerTitle').textContent=titles[k];$('#drawer').classList.add('open');$('#scrim').classList.add('open');$('#drawer').setAttribute('aria-hidden','false');$('#drawerBody').innerHTML='<span class="loader">FETCHING CANONICAL STATE…</span>';app.memory.panels[k]=(app.memory.panels[k]||0)+1;saveMemory();try{const r=await fetch(FILES[k],{cache:'no-store'});if(!r.ok)throw Error(r.status);$('#drawerBody').innerHTML=renderPanel(k,await r.json())}catch(e){$('#drawerBody').innerHTML=`<article class="record"><small>CANONICAL FETCH FAILED</small><h3>${esc(e.message)}</h3><p>Viewer memory remains available locally.</p></article>${k==='memory'?memoryMarkup():''}`}bindMemoryButtons();if(app.audio)ping(420,.025)}
function closeDrawer(){$('#drawer').classList.remove('open');$('#scrim').classList.remove('open');$('#drawer').setAttribute('aria-hidden','true');app.panel=null}
function bindMemoryButtons(){const ex=$('#exportMemory'),cl=$('#clearMemory');if(ex)ex.onclick=()=>{const b=new Blob([JSON.stringify(app.memory,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`kxtxr-viewer-memory-${Date.now()}.json`;a.click();URL.revokeObjectURL(a.href)};if(cl)cl.onclick=()=>{localStorage.removeItem(KEY);app.memory=blankMemory();app.memory.visits=1;saveMemory();openPanel('memory');toast('LOCAL MEMORY CLEARED')}}
async function enter(){await pullRemoteMemory();app.memory.visits=(app.memory.visits||0)+1;saveMemory();$('#boot').classList.add('off');touchScene(app.memory.lastScene||0);if(app.memory.lastScene>0)toast(`PERSISTENCE FOUND · LAST SCENE 0${app.memory.lastScene+1}`)}
function init(){initRunes();setScene(0,true);requestAnimationFrame(animateNodes);addEventListener('scroll',onScroll,{passive:true});addEventListener('resize',()=>drawSignal(progress()));$('#enterSignal').onclick=enter;$('#skipBoot').onclick=enter;$('#soundToggle').onclick=toggleSound;$('#closeDrawer').onclick=closeDrawer;$('#scrim').onclick=closeDrawer;$$('[data-panel]').forEach(e=>e.onclick=()=>openPanel(e.dataset.panel));$$('[data-jump]').forEach(e=>e.onclick=()=>jump(+e.dataset.jump));addEventListener('keydown',e=>{if(e.key==='Escape'){$('#boot').classList.add('off');closeDrawer()}if(e.key==='ArrowDown')jump(Math.min(6,app.scene+1));if(e.key==='ArrowUp')jump(Math.max(0,app.scene-1))});document.addEventListener('visibilitychange',()=>{if(document.hidden){const s=app.memory.scenes[app.scene];if(s)s.ms=(s.ms||0)+(Date.now()-app.last);saveMemory()}else app.last=Date.now()});setInterval(()=>{if(app.scene===5){$('#hotNodes').textContent=143+Math.floor(Math.sin(Date.now()/900)*4);$('#hotSignal').textContent=(97.9+Math.sin(Date.now()/1100)*1.1).toFixed(1)+'%'}},700)}
init();
